"""Add column updated_at in users table

Revision ID: 76774474f1aa
Revises: 86a4dcbb4523
Create Date: 2026-04-16 20:43:56.289518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76774474f1aa'
down_revision = '86a4dcbb4523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
